// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fluxscope/fleet"
)

// Injectors from wire.go:

func wireApp() (*fleet.App, func(), error) {
	app := NewApp()
	return app, func() {
	}, nil
}
